basePath: /
definitions:
  main.Response:
    properties:
      code:
        description: 响应码
        type: integer
      data:
        description: 具体的数据
      msg:
        description: 描述
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact: {}
  description: API文档
  title: API文档
  version: "1.0"
paths:
  /api/users:
    get:
      description: 返回一个用户列表，可根据查询参数指定
      parameters:
      - description: 返回多少条
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
      tags:
      - 用户管理
swagger: "2.0"
